### ISSUE TITLE
encrypt

### ISSUE THREAD

**Issue by jordan12121** [TTFH/fsocietyM#1]
does this encrypt only C:\\Users\\(username)\\testfolder
what if all drives are encrypted all

**Comment by TTFH** [comment]
Add the folder you want to encrypt in [main.cpp#L148](https://github.com/TTFH/fsocietyM/blob/master/main.cpp#L148)
For example: **SearchFiles("C:\\", key);** will encrypt all the drive C, including: **SearchFiles("C:\\Windows\\System32", key);**
Remove [this line](https://github.com/TTFH/fsocietyM/blob/master/main.cpp#L122) if you aren't using Windows 10

**Comment by jordan12121** [comment]
@TTFH  thanks for reply..

does this infect the windows system,
i tried complier g ++ -Wall -Werror -O3 main.cpp aes.cpp base64.cpp random.cpp DRM.cpp -o fsocietyM -Wno-unused-result -fconcepts
yes I see it's output for linux ,
I tried the output to be fsociety.exe and it was run on a virtual machine that could not be started and had no effect

**Comment by TTFH** [comment]
@jordan12121 To compile for windows (.exe file) you need windows, install [msys2-x86_64-20180531](https://www.msys2.org/) and install the compiler from the msys2 terminal, i.e. Open C:\msys64\msys2.exe and type: `pacman -S mingw-w64-x86_64-toolchain`

**Comment by jordan12121** [comment]
is this correct for encrypting files C: \
![ransom](https://user-images.githubusercontent.com/39400825/57110491-2ffe0d00-6ce5-11e9-9cff-ab55359a8152.png)

**Comment by jordan12121** [comment]
![ransom2](https://user-images.githubusercontent.com/39400825/57142370-d0494580-6d68-11e9-82d0-e938cb7a1d4b.png)
error to complier

**Comment by TTFH** [comment]
@jordan12121 Just copy **msys-2.0.dll** from C:\msys64\usr\bin to the folder when you have fsocietyM.exe
If it say you're still missing some other .dll file, do the same.

**Comment by jordan12121** [comment]
@TTFH  no file effect to encryption

**Comment by jordan12121** [comment]
I made a folder in C: \ Users \ (admin) \ testfolder in the testfolder there are several files then I complier with the command g ++ -Wall -Werror -O3 main.cpp aes.cpp base64.cpp random.cpp DRM.cpp -o fsocietyM -Wno-unused-result -fconcepts there is no error when the program starts and there are no file effects to the encryption

**Comment by TTFH** [comment]
@jordan12121 The file fsocietyM.exe (and the .dll) needs to be outside the folder.
mainfolder\fsocietyM.exe
mainfolder\testfolder\example-file1.txt
mainfolder\testfolder\example-file2.png
Make sure to remove [this line](https://github.com/TTFH/fsocietyM/blob/master/main.cpp#L122) if you aren't using Windows 10

**Comment by jordan12121** [comment]
![folder](https://user-images.githubusercontent.com/39400825/57201166-085bae80-6f4a-11e9-8d45-376cfd337162.PNG)
![folder2](https://user-images.githubusercontent.com/39400825/57201167-085bae80-6f4a-11e9-9a06-96e3c64826ee.PNG)

I deleted [the line](https://github.com/TTFH/fsocietyM/blob/master/main.cpp#L122)

**Comment by jordan12121** [comment]
![cli](https://user-images.githubusercontent.com/39400825/57201278-d21f2e80-6f4b-11e9-9962-4d66be4e1b76.PNG)
I tried to drive infection D: \

**Comment by TTFH** [comment]
@jordan12121 
The code to encript D:\ is:
`SearchFiles("D:\\", key)`
**Note the two slashes** (Sorry, github change my other comment)
![Works for me](https://user-images.githubusercontent.com/23284861/57201912-ae70de00-6f75-11e9-9a3f-ee2bcd5f858e.png)

**Comment by jordan12121** [comment]
@TTFH  if the console is removed, how do I know the generalized key id to decrypt the file 
and how to decrypt one file ?

**Comment by jordan12121** [comment]
![mentok](https://user-images.githubusercontent.com/39400825/57208614-a91d8e80-6f89-11e9-8486-3afa039c907c.PNG)
if there are too many encryption process files like this

**Comment by TTFH** [comment]
@jordan12121 Good question, I'll try to fix that later, for now you can:
1) Download [HxD](https://mh-nexus.de/en/downloads.php?product=HxD)
2) Use HxD to open the file **key.bin** located in the same folder as fsocietyM.exe
3) Copy the decryption key (64 characters), it will looks like this:
> 01 23 45 67 89 0A BC DF 67 72 61 6D 20 63 61 6E 6E 6F 74 20 62 65 20 72 75 6E 20 69 6E 20 44 4F
4) Compile the decrypter with: `g++ -Wall -Werror -O3 decrypter.cpp aes.cpp -o decrypter`
5) Open decrypter.exe, paste or type the key, type "Y" (y uppercase)

**Comment by jordan12121** [comment]
I will wait for the repair sir,
you are really great

**Comment by jordan12121** [comment]
![volume](https://user-images.githubusercontent.com/39400825/57271733-18a08600-703d-11e9-86bc-b2386e3eb2b8.PNG)
Why did it happen
"System volume information"

**Comment by jordan12121** [comment]
@TTFH  if the cryptowall file is not on the victim's PC, the full screen message will not appear

**Comment by TTFH** [comment]
@jordan12121 Right, for now that's expected behavior. Someone made a modification of my code to add the message into the code, i'll try to implement that in the future. [DailyAllowance](https://github.com/fuxsocy/DailyAllowance)

**Comment by jordan12121** [comment]
it only infects Linux [DailyAllowance](https://github.com/fuxsocy/DailyAllowance)

**Comment by jordan12121** [comment]
@TTFH  it would be better if ID.txt follows the folder that was infected

**Comment by jordan12121** [comment]
Hello @TTFH new problem 
I tried to put the fsocietyM file in D: / with the jpg file php html bmp etc.
Then why is fsocietyM also encrypted too, so the process of encrypting the file stops

**Comment by Gembeltz** [comment]
hello sir 
help me please, error complier

**Comment by Gembeltz** [comment]
this is error

**Comment by Gembeltz** [comment]
e

**Comment by Gembeltz** [comment]
make
g++ -Wall -Werror -Iheaders -Wno-unused-result -fconcepts -c main.cpp -o obj/main.o
Assembler messages:
Fatal error: can't create obj/main.o: No such file or directory
make: *** [makefile:22: obj/main.o] Error 1

**Comment by Gembeltz** [comment]
make
g++ -Wall -Werror -Iheaders -Wno-unused-result -fconcepts -c main.cpp -o obj/main.o
Assembler messages:
Fatal error: can't create obj/main.o: No such file or directory
make: *** [makefile:22: obj/main.o] Error 1

**Comment by Gembeltz** [comment]
@TTFH a little difficult if the cryptowall file must be sent to the victim,
 if the cryptowall file added to% tmp% is perfect
